Final
webmarkyn/micro-floating pull request #2
Opened 2019-09-18 22:24 UTC by webmarkyn

2019-09-19 19:19 UTC, stratospherique reviewed
### Pull request under review by Ahmed Mahfoudh TSE

2019-09-19 19:59 UTC, stratospherique requested changes
### Splendid work team :clap: . However, in order to get approval for this project, further changes needs to be made. check below :arrow_down: 

#### main content

- **[REQUIRED]** You footer width is causing an horizontal scrolling effect on you page. :pray: fix it
![image](https://user-images.githubusercontent.com/26124023/65276743-526fb600-db20-11e9-8421-5a67555578ad.png)

- **[REQUIRED]** Check the original page and try to add a similar bottom banner that is fixed at the bottom of the viewport to you page.
- **[REQUIRED]** Add more info to your readme file ( a short description of the project, technologies used , link to the assignment, link to your github profiles, etc...)

##### Bottom part
* [ ] It contains links to other articles with image previews on the leftmost side.
* [ ] It contains links to more popular articles on the rightmost side.

- **[:skull:]** I saw the list of commits and I noticed that you are not using the regular workflow (30min-switch). @rkyankya has done only the first commit. :worried: . Can you explain it guys ?

### That's it guys :relaxed: . When finished, kindly resubmit another code review form :pray: .

2019-09-19 22:17 UTC, webmarkyn commented
@rkyankya get errors when trying to push to this project so he's giving me his code packed in zip and I push it.

2019-09-20 07:45 UTC, samgaco approved these changes
Hi @webmarkyn  and @rkyankya :high_brightness: 

Good job, the project is approved :white_check_mark: you may merge to the master branch and submit the project completion form.

-----------------------------
* **About your issue,** try to find out what is happening and solve it so you both can commit in your next projects :pray: 
--------------------------------

Have this into account moving on :arrow_down: 
* Friendly reminder: You should use [Github flow](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/) in your projects. For example now you are doing the pull request from a development branch, but it should be from a feature branch (some name that represents the feature you are working on). Please make sure you use [Github Flow](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/) in the next project. 
* **[For your next code review requests]**  Use meaningful names for your Pull Requests
* **[For your next code review requests]**  Add a short summary of changes in Pull Request description

----------------------
* ###### STATUS OF THE PROJECT: APPROVED :heavy_check_mark:

2019-09-20 07:45 UTC, samgaco commented on styles.css
> +  left: 0;
:+1:

2019-09-20 07:45 UTC, samgaco commented on README.md
> +## Description
You can still make the readme file look more professional, find inspiration [here](https://github.com/othneildrew/Best-README-Template) or [here](https://www.udacity.com/course/writing-readmes--ud777).

2019-09-20 08:32 UTC, merged